### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#106]
Add unit tests so we have bare bones testing functionality.

**Comment by lenmorld** [comment]
The initial setup and tests should be covered by 
- Issue https://github.com/WildAid/o-fish-web/issues/317: PR https://github.com/WildAid/o-fish-web/pull/424
- Issue https://github.com/WildAid/o-fish-web/issues/316: PR https://github.com/WildAid/o-fish-web/pull/376

Should we close this and re-create individual issues for each test?

**Comment by o-fish-wildaid** [comment]
Sure! Will close. I'd love issues for tests! Let me know if you need help making issues (if you have a list of tests in mind).

Thanks for the PR!

**Comment by lenmorld** [comment]
@o-fish-wildaid 
I was thinking we can start with the unit tests for each component, like maybe one issue per component in `src/components`, one issue per service in `src/services` and one issue per file in `helpers`. That would be a good start, I think.

I'll start creating some of these, but it's a lot so I'll need some help to create for all.

I'll also create an issue to setup e2e tests. I'd actually want to take a stab on that, something like Cypress, or puppeteer :)

And also, we can also encourage tests on new code coming in, either new features or bug fixes. We can either document this in the contribution guide and/or during code reviews. 

What do you think?

**Comment by Sheeri** [comment]
That all sounds great! I'm happy to have an issue that's something like "create github issues for unit tests for everything in components" and another for "everything in services", etc. so we can track the "paperwork" too.

If you can give me a list of the tests needed, I can pop those into a file to import into Github issues.

WRT new testing, we can do both! Feel free to do a PR for those, or if you don't want to do that, I'm sure I'll get around to it before hacktoberfest.
