### ISSUE TITLE
Change own password

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#108]
User should be able to change their own password through the 'My Account' link in the upper right profile menu - as documented here - https://docs.google.com/document/d/1rDXmdlB3lfqAb7uAhR1u96LbyNaUyl3_2t2O_C0kI_E/edit?pli=1#bookmark=id.fm2m7txszq6 and designed here - https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/422332164 (click the 'change password' button)

**Comment by Sheeri** [comment]
@brittanylau this would be a great one to take if you have some time!

**Comment by brittanylau** [comment]
@Sheeri sounds good, I'll check it out tomorrow! :)

**Comment by Sheeri** [comment]
Ok. Just FYI this involves realm so let me know if you don’t have a build environment set up, I can get you access to my test env.

**Comment by brittanylau** [comment]
@Sheeri it seems that changing Realm user passwords can only be done through a [password reset](https://docs.mongodb.com/realm/web/manage-email-password-users/#complete-a-password-reset). Realm's password reset function requires we pass in a `token` and `tokenId`, which can only be retrieved from an email sent to the user.

I could be misunderstanding the docs, so let me know if any Realm experts have other ideas! :)

Here's what would be needed:
1. Send an email to the user to confirm their identity (valid for 30 mins)
2. User clicks on a password reset link provided in the email (Realm appends the `token` and `tokenId` as query parameters)
    - URL and email subject are customizable
<img width="1202" alt="Screen Shot 2020-09-12 at 6 21 42 PM" src="https://user-images.githubusercontent.com/37346399/93005977-d175af80-f524-11ea-9d6f-b0db61fde5c0.png">

3. User enters a new password on the page

Where should we integrate these extra steps in the flow?

**Comment by brittanylau** [comment]
Nevermind! I misunderstood the docs after all :) PR coming in shortly!
