### ISSUE TITLE
Default time for date picker

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#109]
Default time for the start date picker should be 00:00 and default time for the end date picker should be 23:59.

**Comment by brittanylau** [comment]
Is this referring to the date picker on the global dashboard, or are there other instances that this should apply to?

**Comment by Sheeri** [comment]
Date picker on the global dashboard.

**Comment by joquendo** [comment]
Hi @Sheeri, I would like to work on this one.
