### ISSUE TITLE
Crew overview page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#117]
From the 'all crew' page following this design - https://mongodb.invisionapp.com/share/2SWVCLE8WJG#/screens/413644457 - when you click on an individual record you get to the crew overview page which looks like this: 
https://mongodb.invisionapp.com/share/2SWVCLE8WJG#/screens/413646957 - 

The most recent picture of the crew member appears next to their name at the top.

Blocks exist for associated Vessels; License Numbers; Boardings; Violations; Photos; and Notes. 

This ticket covers the functionality of this page - note that NONE of the 'See All' links or "View Boarding" buttons need to work for this ticket to be considered complete. 

Each block has a count of the total number of items in the upper right hand corner. 

For Vessels and License Numbers list the most recent 3 associations - they should be DIFFERENT (the design shows the same 3 vessels but it should show 3 unique vessels - unique by name and permit number) If the count is >3 then a 'See All' link should appear but it does not need to be functional right now. 

Boardings should show the 5 most recent boardings (not 6 like the design shows) with the fields as shown; 'See All' appears if there are more than 5 boardings but does not have to work yet. 

The Violations section should have the 5 most recent Violations with the information shown and a 'See All' link if there are more. 'See All' and the 'View Boarding' button don't need to work yet. 

The most recent 12 photos should appear in Photos with a 'See All' link if there are more than 12. The most recent 5 notes (not 6 like in the design) should be in the Notes block with a 'See All' link if there are more than 5.

**Comment by jsdmaria** [comment]
**In scope of 8/18 milestone:**
1) crew overview redesign is done;
2) page is switched to DB (real data added)

**In scope of 8/25 milestone we plan to:**
1) add redirecting links (e.g. 'See all' link in blocks)
2) add necessary pages (as it shown in newest designs such as - https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/427645091)
