### ISSUE TITLE
Dates and Time Zones

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#133]
When I use the date picker on the Dashboard page to find records for Jul 29 2020 00:00 to Jul 29 2020 23:59 I find 1 record - Magic boarded at 11:32. However when I search for Jul 28 2020 to Jul 30 2020 I see there are 3 other boardings all between 00:00 and 01:01. I believe these are not showing up due to time zone issues. Please make sure the date picker does not pass along time zone information.

**Comment by Sheeri** [comment]
This looks like it has been fixed - the dates and timestamps in the boarding record database are stored as +00:00 time zone, and retrieved as such in the search.
