### ISSUE TITLE
Boarding Details page does not work when there are undefined items

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#134]
If I do a search for the boarding of the Orca on Aug 4 2020 and click on the boarding record - I get an error 'TypeError: item.attachments is undefined'. If I try to click on the boarding record for the vessel Test with permit number 12345 on Aug 5 at 9:09 am I get 'TypeError: crew is undefined' (and indeed there are no crew members). If there are undefined items the Boarding Details page should still work.

**Comment by am-MongoDB** [comment]
@jsdmaria I see that this is set to "Review in progress" – is there a PR that should be linked to this issue?
