### ISSUE TITLE
Vessel page should show boarded by

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#147]
Boarded by is blank on the individual vessel page:

![Screen Shot 2020-08-11 at 1 52 40 PM](https://user-images.githubusercontent.com/1767528/89931684-8a6d6500-dbda-11ea-9fa8-f983ccb55f80.png)

**Comment by brittanylau** [comment]
Hi @Sheeri, what are the steps to reproduce? I can see the values for the vessels in my dev environment, though I've only spot-checked a few.

<img width="1536" alt="Screen Shot 2020-09-06 at 3 20 31 PM" src="https://user-images.githubusercontent.com/37346399/92333569-82c3a380-f054-11ea-8394-d6a383950975.png">

**Comment by Sheeri** [comment]
Hrm, it appears the issue has already been fixed. Closing!
