### ISSUE TITLE
Create user makes a pending realm user

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#151]
If I create a user, logout and try to login with that new user I can't. When I look into it, the database user is created just fine with all the data (agency, first name, etc) - but in Realm the user is in the "pending" category. I don't know how to fix that....

**Comment by Sheeri** [comment]
cc @am-MongoDB

**Comment by Sheeri** [comment]
cc @Azzoo this is the ticket I was talking about to make sure that create user works properly.

**Comment by Sheeri** [comment]
@am-MongoDB fixed this I believe, it's OK that it's pending, it was a bug in what password to use. Will confirm after today's build.

**Comment by am-MongoDB** [comment]
Fixed under [PR166](https://github.com/WildAid/o-fish-web/pull/166)
