### ISSUE TITLE
Agency choice of preferred flag state should be a pull-down menu

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#155]
As per the design at https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/424365384

Adding a preferred flag state should be picking from a country list.

We can use the country list (already localized to many languages) from:
https://github.com/umpirsky/country-list
It is an MIT license so acceptable to use.

**Comment by Sheeri** [comment]
Note that the value saved in the database should be the 2-digit country code.

**Comment by brittanylau** [comment]
Hey @Sheeri, happy to look into this one! Could you please share some context on what an agency's preferred flag states are used for throughout the app?

**Comment by Sheeri** [comment]
Absolutely! (one of the things I'm going to work on is a demo video of the app, btw, which should answer a lot of these).

Preferred flag state is used in the mobile app, when creating a boarding record. There is a field called "Flag State" which is the country the boat is registered to. Because each agency is working in a specific geographic region, there are countries that are more frequently seen than others. e.g. for the Galapagos islands, Ecuador and Panama are seen most often.

Preferred flag state is a list of up to 5 countries that will appear at the top of the menu selector in the mobile apps for Flag State. In this way, a user does not have to scroll down to Panama to select it, it is conveniently right at the top. (folks in the United States are very familiar with this - having USA and Canada right at the top of the list instead of having to scroll all the way down to select it.)

Let me know if that's not clear!

**Comment by brittanylau** [comment]
This is super helpful, thank you! Looking forward to the demo video :)

A couple questions:

1. If only up to 5 countries are displayed, is there a limit to how many flag states can be added?
2. I noticed the form data page currently looks a bit different to the designs linked above (screenshot of current page below). Is that something we're hoping to move toward, or are there updated designs somewhere?

<img width="1284" alt="Screen Shot 2020-09-09 at 6 20 39 PM" src="https://user-images.githubusercontent.com/37346399/92806275-d5b89600-f387-11ea-9aa7-24b7dccbdc06.png">

**Comment by Sheeri** [comment]
1. I think a screenshot may be more clear. Here's the ios application - on the "vessel information" screen:
![IMG_9025](https://user-images.githubusercontent.com/1767528/92808628-e964fc00-f389-11ea-9d7f-9565cd7b7395.PNG)

The "Flag State" space, when selected by the user, pops up a menu that looks like this:
![IMG_9024](https://user-images.githubusercontent.com/1767528/92808615-e79b3880-f389-11ea-9fe0-da8527e18108.PNG)

ALL the countries of the world are represented, but Ecuador and Panama are given preferential treatment. 

Note that they should be added in the order the user adds them, not necessarily alphabetical order. e.g. the preferred flag states might be:
United States
Canada
and they should appear like that in the list, with united states first. It just happens in this case that Ecuador is the most popular Flag State for this agency, which is in the Galapagos :D 

2. We'd like it to look like the designs if possible. We totally understand if you keep the design elements as they are now, though. Completion of this ticket depends on the functionality, not changing the design to match; of course we'd be appreciative if things get moved towards that way!

**Comment by brittanylau** [comment]
Thanks for the clarification! This context is super useful.

I'll get the functionality for adding flag states working first! :) The design update for Agency Admins seems closely related to #176 and #177, so that'll be great to keep in mind when those get implemented.

**Comment by Sheeri** [comment]
Verified complete.
