### ISSUE TITLE
Crew all page -> Search should work by Crew member name and license #

### ISSUE THREAD

**Issue by jsdmaria** [WildAid/o-fish-web#157]
On Crew overview

**Comment by Sheeri** [comment]
Vessel should be a comma separated list. See design at https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/427643117_Agency_Admin-Crew - Mike Nemo has 3 vessels. For now, let's show up to 50 characters and after that use ... to indicate more.

**Comment by Sheeri** [comment]
@jsdmaria - This was something you asked to be priority for this week. Note that this should also work for if there is a blank license number.

Ideally this would show up as filters for name, and license number (if license number exists). For now it's OK if it's just a search, but if it's something that can be combined in this ticket that's great too.
