### ISSUE TITLE
Field officer Users menu and permissions

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#172]
A user with a 'field officer' role should not have a pulldown menu for Users - they can only see 'All Users'. Once on the page they should only be able to see and search for users as per https://mongodb.invisionapp.com/share/7FXRXCBTYEW#/screens/422322414_Field_Officer-Users - they should NOT be able to edit. As well they should see 'Name' 'Role' 'Email' 'Status' as per the design (we do not have greoups yet so that can be left out) - they do NOT need to see 'Created On'.

**Comment by jsdmaria** [comment]
Added users permissions for Global Admin and Agency admin
