### ISSUE TITLE
Edit Agency functionality

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#178]
Create the "Edit Agency" page as per https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/424650605

"Active" is a toggle button, everything else is a text field.

They get stored in the Agency collection as follows:

Status gets saved as a boolean to the "active" field
Agency Name gets saved as "name"
Description gets saved as "description"
Website gets saved as "site"
Contact Email gets saved as "email"

Connect the page in 2 places (can click through the design at https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/424650604 to see both):
Agencies page, then click "Edit" at the end of a row
or
Agencies page, then click the Agency name (Parque Nacional Galápagos), then click the "Edit Agency" button in the top right.

**Comment by brittanylau** [comment]
Hey @Sheeri, are issues under the Hacktoberfest label up for grabs before October (hacktemberfest maybe)? Happy to give this a shot :)

**Comment by Sheeri** [comment]
@brittanylau absolutely, hacktoberfest issues are up for grabs any time! (sorry for the delay, long holiday weekend!)

**Comment by brittanylau** [comment]
@Sheeri sounds good - hope you had a relaxing weekend!
