### ISSUE TITLE
Allow lastDelivery to be optional/null

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-web#184]
The iOS app has been updated to set `lastDelivery` to be optional in the Realm model: https://github.com/WildAid/o-fish-ios/pull/269

If the user doesn't provide any details for the 'lastDelivery` then it should be set to `null`.

When viewing a report, the app should cope with `lastDelivery` being set to `null`.

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise new issues resulting from using/testing the apps](https://trello.com/c/npsrp2yZ/217-raise-new-issues-resulting-from-using-testing-the-apps)
