### ISSUE TITLE
Add "Create New User" button to All Users page

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#189]
As per this design, please add a "Create New User" button to the [All Users](https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/422136442_Agency_Admin-Users) page (link below)

https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/422136442_Agency_Admin-Users

The All Users page is the /users page

This is ONLY for Global Admins and Agency Admins. NOT for Field Officers.

**Comment by evayde** [comment]
Is this already done?

I saw this in the source `src\components\users\users.component.js:161`
```
          {(isAgencyAdmin || isGlobalAdmin) && (
            <div className="flex-row align-center padding-right">
              <NavLink to={USERS_ACTIVITIES_PAGE} className="blue-btn">
                {t("BUTTONS.CREATE_REPORT")}
              </NavLink>
              <NavLink className="white-btn" to={NEW_USER_PAGE}>
                {t("NAVIGATION.ADD_NEW_USER")}
              </NavLink>
            </div>
          )}
```

which seems about right.

**Comment by Sheeri** [comment]
Yes, this was indeed completed. Apologies that it was not closed.
