### ISSUE TITLE
Replace Edit Icon on All Users Page with the word "Edit" (link)

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#190]
On the All Users page (url is /users), replace the edit icon
![Screen Shot 2020-09-15 at 5 13 09 PM](https://user-images.githubusercontent.com/49571712/93265668-f2cdda00-f776-11ea-989f-b930dbd17faa.png)

with the word edit as per the [design](https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/422136442_Agency_Admin-Users)

![Screen Shot 2020-09-15 at 5 13 19 PM](https://user-images.githubusercontent.com/49571712/93265711-02e5b980-f777-11ea-92bb-24ea0191bdb1.png)

This is ONLY for Global Admins and Agency Admins. The Edit option should NOT exist for Field Officers.

**Comment by Sheeri** [comment]
@jsdmaria I think you're already working on this page so this should easily fit with this week's tasks.
