### ISSUE TITLE
Nav menu items for Global Admin are incorrect

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#196]
**Agencies**
Agencies should not have a drop down
Issue:
![Screen Shot 2020-09-16 at 11 10 46 PM](https://user-images.githubusercontent.com/49571712/93415675-10339e80-f872-11ea-83f2-b95b8752cfdc.png)

Should be:
![Screen Shot 2020-09-16 at 11 13 14 PM](https://user-images.githubusercontent.com/49571712/93415741-38bb9880-f872-11ea-9d39-19f09f206781.png)

**Users**
Users menu options should be "All Users" and "User Groups"

Issue:
![Screen Shot 2020-09-16 at 11 10 50 PM](https://user-images.githubusercontent.com/49571712/93415799-58eb5780-f872-11ea-9147-d1fd79eae456.png)

Should be:

![Screen Shot 2020-09-16 at 11 11 34 PM](https://user-images.githubusercontent.com/49571712/93415814-5f79cf00-f872-11ea-893c-445e14de7d32.png)

**Comment by Sheeri** [comment]
Verified.
