### ISSUE TITLE
Create guest developer user & agency for Hacktoberfest

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-web#197]
This functionality is to support users creating their own agency-admin user in a shared instance of the O-FISH Realm app.

There is a matching web issue for this feature: https://github.com/WildAid/o-fish-realm/issues/136

- [ ] There should be a new config flag to enable/disable this new page (unauthorised error if the flag isn't set).
- [ ] There needs to be a new page `#/users/new_dev_user` that's based on `#/users/new_user`.

The page should look something like this (this is a "backdoor" for developers and so the design doesn't need to be precise):

![image](https://user-images.githubusercontent.com/14197449/93568554-3f3c3400-f988-11ea-8629-8346289ae1a9.png)

All of the fields are free text.

When the button is pressed the following should be done:

- [ ] Log into Realm using anonymous authentication
- [ ] Call the Realm function `regDevUserAgency` passing in first name, last name, email, agency name and agency url as arguments(in that order
- [ ] If the function returns an error then display that error (errors could include "Agency already exists" or "User already exists", ...)
- [ ] Create the Realm username/password user (but **do not** add a document to the `User` collection as that's already been done by the `regDevUserAgency` function
- [ ] If the function returns successfully then automatically log in as that user and redirect to `/#/home` (or redirect to the login page if that's a lot simpler

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create issues for Hacktoberfest guest agency creation](https://trello.com/c/lzDYKBjq/320-create-issues-for-hacktoberfest-guest-agency-creation)

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement developer agencies for Hacktoberfest - web](https://trello.com/c/TpfS0Bhc/322-implement-developer-agencies-for-hacktoberfest-web)

**Comment by Sheeri** [comment]
@brittanylau is this something you are up for doing? @am-MongoDB will be working on the Realm function regDevUserAgency so you can use a placeholder function that succeeds (or fails) and testing that way.

**Comment by brittanylau** [comment]
@Sheeri I'm up for it! I can work on this during the weekend.

**Comment by brittanylau** [comment]
Hey @Sheeri, I'm slowly picking away at this one (haven't had as much time as I thought) - are there any dependencies/deadlines for this, aside from being ready for Hacktoberfest?

**Comment by Sheeri** [comment]
Hi @brittanylau - Being ready for hacktoberfest includes needing time for testing; It would be great to have a PR submitted by noon UTC on Monday. If not, that's totally OK, just let us know so we can reassign.

**Comment by brittanylau** [comment]
@Sheeri that timeline is perfect! Thanks for the heads up :)

**Comment by brittanylau** [comment]
@am-MongoDB quick clarification! Should users be able to access this page (and create a new user) without logging in first?

**Comment by am-MongoDB** [comment]
@brittanylau - yes. This page is only enabled if you want to provide a sandbox environment for developers to test the web or mobile apps against. The idea is that we host the backend environment (including the web site) and developers can come to this page to create their own agency and user account, which can then be used for testing. Because everything is partitioned by agency, only users registered against this agency will see the data they then add using the apps.

**Comment by brittanylau** [comment]
Thanks @am-MongoDB! This context is very helpful - I'll get a PR out by Monday.
