### ISSUE TITLE
Agencies Dashboard Title

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#205]
As per the design at https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/422348690_Global_Admin-Home-Dashboard - When the global administrator clicks on Dashboards in the top nav and then Agencies; the resulting page at /global_agencies should show a title of 'Agencies Dashboard'. Currently it says 'Agencies'.

**Comment by fgiuliani** [comment]
@o-fish-wildaid can I work on this?

**Comment by am-MongoDB** [comment]
@fgiuliani Yes please go ahead!

**Comment by k-charette** [comment]
I was able to complete this issue on my local machine. I noticed that there hasn't been any updates in a week. Would it be alright if I put in my PR for review regarding this?

**Comment by Sheeri** [comment]
Absolutely, please do!

**Comment by Sheeri** [comment]
@fgiuliani According to the contribution guidelines at https://wildaid.github.io/contribute/index.html - we consider an issue that hasn't been commented on in 72 hours to be abandoned. As such, we have re-assigned it. 

If you have time to code, we still have plenty of other issues to work on!

**Comment by fgiuliani** [comment]
@Sheeri sorry not answering before. I was planning to work on this as part of Hacktoberfest. And as I asked about this issue before October, I was planning to wait.

My bad. Sorry again @Sheeri @k-charette
