### ISSUE TITLE
Global Admin Dashboard nav

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#206]
As per the design at https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/422348690_Global_Admin-Home-Dashboard - The top nav item between the O-FISH logo and 'Boarding Records' currently shows as 'Dashboard'. It should be 'Dashboards'.

**Comment by rishabhmishra25** [comment]
I would love to contribute for the same, Please assign the same to me!

**Comment by Sheeri** [comment]
@rishabhmishra25 thanks for offering to do this. I have assigned it to you.

**Comment by rishabhmishra25** [comment]
> @rishabhmishra25 thanks for offering to do this. I have assigned it to you.

Thanks! I'll prepare the edits and make a pull request on 1st october!

**Comment by Sheeri** [comment]
@rishabhmishra25 if you prepared the edits, please don't forget to submit them!

**Comment by Sheeri** [comment]
This has been done.
