### ISSUE TITLE
Skinning - Boardings - Filter should look like this

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#21]
https://mongodb.invisionapp.com/share/W2XD0U23F8H#/screens/418359759_Agency_Admin-Search-Boardings_Filter_Dropdown

**Comment by crowtech7** [comment]
Has this already been done? Or does the order of the alerts needing to change to "green, amber, red" from "red, amber, green"?

**Comment by Sheeri** [comment]
This has been done - good eye @crowtech7 ! Thanks for catching that.

If you'd like to get hacktoberfest credit because you did work researching this, feel free to open a PR against this issue - we will close it without merging it, but we will not mark it invalid.

**Comment by Sheeri** [comment]
@crowtech7 if you're looking for a bug to ease you into the codebase, I recommend looking at https://github.com/WildAid/o-fish-web/issues/277 - I just made it.
