### ISSUE TITLE
Field Officers Edit Profile

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#210]
When a Field Officer clicks their name in the upper right and then 'My Account' - they are currently able to select Role and Agency from a menu. The menu is limited to their current role and agency, so they can't actually change anything. This screenshot is after clicking Agency, which brings up a selection menu of 1 agency:
![Screen Shot 2020-10-02 at 1 01 00 PM](https://user-images.githubusercontent.com/1767528/94949682-54987e80-04af-11eb-94f7-4628328e5546.png)

However field officers shouldn’t even be able to click on the role or group fields. As per the design at https://mongodb.invisionapp.com/share/7FXRXCBTYEW#/422216178_Field_Officer-My_Account

**Comment by lenmorld** [comment]
Hi, I'd like to try this

**Comment by Sheeri** [comment]
Hello @lenmorld , thanks for offering to work on this! I have assigned it to you.
