### ISSUE TITLE
Officers in the Agency Admin Interface

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#212]
When an agency administrator clicks Agencies in the top nav - and then clicks on an agency - they get to the /agencies/view_agency page. The first tab is 'Officers' and currently shows 0 officers: 
![Screen Shot 2020-10-02 at 12 53 46 PM](https://user-images.githubusercontent.com/1767528/94949061-5281f000-04ae-11eb-8295-a03ad0ee39be.png)

As per the design at https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/424650597 the page should show all the users in the agency. 

There should be a count of officers; a search bar; and an 'Add New User' button. Then a list of officers should display sorted alphabetically - ascending by last name. Each officer's row should display: Name - Group - Role - Status and a link to 'Edit' the user. For this issue to be considered complete the search bar does NOT have to work. The 'Add New User' link should work and go to the /users/new_user page.

**Comment by deveshchatuphale7** [comment]
Hi @Sheeri , I would like to work on this.

**Comment by Sheeri** [comment]
Hello @deveshchatuphale7, thanks for offering to work on this! I have assigned it to you.
