### ISSUE TITLE
Officer search in the Agency Admin Interface

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#213]
When an agency administrator clicks Agencies in the top nav - and then clicks on their own agency - they get to the /agencies/view_agency page. The first tab is 'Officers' and should have a search bar. This ticket is to make the search bar work against the following fields in the User table: name.first; name.last; email.

This depends on issue #212 being completed.

**Comment by deveshchatuphale7** [comment]
Hi @Sheeri I would like to work on this issue

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you @deveshchatuphale7.
