### ISSUE TITLE
Data Sharing Agency Admin top nav and page UI

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#216]
Agency Administrators should have a 'Data Sharing' link on the top nav which brings them to a page that looks like this: https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/428492020 - Right now I don't have a blank design but I will update this issue when I have one. For now the Data Sharing page does not need to have any functionality - just the design/container. When the database schema is ready there will be more issues to load from the database.

**Comment by Sheeri** [comment]
Confirmed the design exists.
