### ISSUE TITLE
Default Homepage for Global Admins

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#217]
For global admins the default homepage upon logging in should be the global dashboard (the /global_agencies page - the page you get if you click 'Dashboard' -> 'Agencies').

**Comment by Bhavik-Ardeshna** [comment]
Hey I ready to work on this issue

**Comment by Bhavik-Ardeshna** [comment]
But I am stuck with design and how i login as global admin

**Comment by am-MongoDB** [comment]
At the moment, you need to create your own Atlas and Realm environment – you can then select your own password. See https://github.com/WildAid/o-fish-realm for details

**Comment by Bhavik-Ardeshna** [comment]
Is there any Discord Server Whicjh I can join to contact for query

**Comment by Bhavik-Ardeshna** [comment]
Hey @am-MongoDB I am not getting code becauz I m new to this field so I cant work

**Comment by am-MongoDB** [comment]
Could you please explain a bit more what problem you're having?

**Comment by Bhavik-Ardeshna** [comment]
its very high level proj for me my basics are not strong tu deal with this

**Comment by RitikPandey1** [comment]
I would like to work on this

**Comment by RitikPandey1** [comment]
@am-MongoDB I would like to take this task

**Comment by am-MongoDB** [comment]
@RitikPandey1 - all yours!

**Comment by RitikPandey1** [comment]
@am-MongoDB  I have created realm backend and also created user on database, but after login I was getting this error    
 
![error](https://user-images.githubusercontent.com/57366926/94560514-6942ff80-0280-11eb-8dc2-b6549c71375e.PNG)

**Comment by am-MongoDB** [comment]
A couple of things to check:

[ ] Have you set `realmAppId` in `config.js` to match your Realm app
[ ] Using the Realm UI – do you see logs confirming that you'd logged in and/or an error log for the missing function?
[ ] Using the Realm UI, go to `Functions` and confirm that `getDashboardStats` is there

**Comment by RitikPandey1** [comment]
> A couple of things to check:
> 
> [ ] Have you set `realmAppId` in `config.js` to match your Realm app
> [ ] Using the Realm UI – do you see logs confirming that you'd logged in and/or an error log for the missing function?
> [ ] Using the Realm UI, go to `Functions` and confirm that `getDashboardStats` is there

Ok , I'll check  these things

**Comment by RitikPandey1** [comment]
@am-MongoDB  I was just checked  "getDashboardStats" function is missing in realm functions , I try again to import realm code  from repo but getting this error 
![err2](https://user-images.githubusercontent.com/57366926/94590490-5a6e4400-02a4-11eb-816f-489f92298025.PNG)

**Comment by RitikPandey1** [comment]
I was just follow the doc https://wildaid.github.io/foundation/2020/06/09/Import-Realm-Code.html and not too much familiar with realm apps, please help

**Comment by RitikPandey1** [comment]
I'm not too familiar with realm apps, please help

**Comment by am-MongoDB** [comment]
@RitikPandey1 Something odd seems to have happened when you did the initial import. if the other functions are there (there should be a lot of them) then you could add `getDashboardStats` through the UI - the code and config can be found at https://github.com/WildAid/o-fish-realm/tree/main/WildAidDemo/functions/getDashboardStats

**Comment by RitikPandey1** [comment]
> @RitikPandey1 Something odd seems to have happened when you did the initial import. if the other functions are there (there should be a lot of them) then you could add `getDashboardStats` through the UI - the code and config can be found at https://github.com/WildAid/o-fish-realm/tree/main/WildAidDemo/functions/getDashboardStats

Thanks , it worked now

**Comment by Sheeri** [comment]
🎉 🙌 🎆 Woo hoo! this issue has been fixed.
