### ISSUE TITLE
Default Homepage for Agency Admins

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#218]
For agency admins the default homepage upon logging in should be the agency dashboard (the /agency_charts/AGENCYNAME page - the page you get if you click 'Dashboard' -> AGENCYNAME).

**Comment by RitikPandey1** [comment]
I would like to take this up

**Comment by am-MongoDB** [comment]
Hi @RitikPandey1 I've assigned this one to you
