### ISSUE TITLE
Homepage for Global Admins

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#219]
Please make sure to read the contribution guidelines at https://wildaid.github.io/contribute/index.html

For global admins the default homepage upon logging in should be the global dashboard (the /global_agencies page - the page you get if you click 'Dashboard' -> 'Agencies').

**Comment by RitikPandey1** [comment]
Hey , I'd like to work on this.
But I'm stuck on login page, how can I login ? 
@o-fish-wildaid  @Sheeri @10genjen @mfhan @dcoupal

**Comment by Sheeri** [comment]
Hi Ritik,

For Global Administrator, you will need to build your own instance. It's free to do, but will take some time. The instructions are at https://wildaid.github.io/build/ - You only need to build the foundation and the web application. Part of the build process has you making a global administrator, so you'll be ready as soon as you're done.

Let us know if you'd still like this ticket, and we will assign it to you, or if you'd rather work on an issue that has less setup involved.

**Comment by RitikPandey1** [comment]
@Sheeri  I am working on this task , i think there is two same issues  #217.

**Comment by Sheeri** [comment]
Oh! You're right, this is a duplicate, I will close this one, as you are assigned to #217 already. Thanks for letting me know!
