### ISSUE TITLE
Skinning - Boardings - Filter Selected should look like this

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#22]
https://mongodb.invisionapp.com/share/W2XD0U23F8H#/screens/418359760_Agency_Admin-Search-Boardings_Filter_Entered

**Comment by crowtech7** [comment]
I'll take this issue! .take

**Comment by Sheeri** [comment]
@crowtech7 I've assigned this to you - thanks for offering to work on it!
