### ISSUE TITLE
Field Officer New User permissions

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#220]
Field officers can change their URL to https://instance/#/users/new_user - they should get an 'Not authorized' page such as when the field officer tries to go to #/agencies

**Comment by stennie** [comment]
I would like to work on this issue

**Comment by Sheeri** [comment]
Hello @stennie, thanks for offering to work on this! I have assigned it to you.

**Comment by stennie** [comment]
@Sheeri According to the [O-FISH Sandbox Guide](https://wildaid.github.io/contribute/sandbox.html) I should be able to create new field officer users with my dev agency account.

When I login with my sandbox agency test account and attempt to create a user I'm encountering a non-obvious error. I tried locally first, and then via https://wildaidsandbox-mxgfy.mongodbstitch.com/#/users/new_user.

I end up with an empty error message box and the Chrome console shows a resource failed to load with an HTTP 409 error ("Resource conflict"):

<img width="1169" alt="create-field-officer-error" src="https://user-images.githubusercontent.com/15554/96360380-86c10600-1168-11eb-93bc-186ff062a24e.png">

Do I need to stand up my own test instance or should this be working? Should I raise an issue for the uncaught error message?

Thanks,
Stennie

**Comment by Sheeri** [comment]
Hi @stennie!

Thanks for catching this - I found the error the other day and attempted to fix it with https://github.com/WildAid/o-fish-realm/pull/172 - I had tested it in the sandbox server, so thought it was working. Andrew fixed the "rules" component and I hadn't changed the sandbox server back. 

It should be working now; can you give it a try please? Thanks!

**Comment by stennie** [comment]
Thanks @Sheeri! User creation in the sandbox is working for me now 👍

**Comment by Sheeri** [comment]
Woo woo! Closing this issue as it's working for you now.

**Comment by stennie** [comment]
@Sheeri I was going to suggest reopening this since the sandbox fix only let me progress testing the issue.

However, it seems the permission check was already added by way of 6d897b64 so there's nothing to do for this issue 👍 

Regards,
Stennie
