### ISSUE TITLE
Agency Admin and Global Admin top nav

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#221]
For Agency Administrators and Global Administrators - the top nav should have a menu called 'Dashboards'. Currently it is 'Dashboard' which is incorrect.

**Comment by nidhishs** [comment]
Hey, I'd like to work on this

**Comment by am-MongoDB** [comment]
Hi @nidhishs – welcome to the O-FISH project! I've assigned this issue to you
