### ISSUE TITLE
Agencies Dashboard for Global Administrator should filter by date

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#233]
The Agencies Dashboard at /#/global_agencies (Dashboard->Agencies for the global administrator) shows all the agencies with their boardings/violations/compliance rate. However it shows those numbers for all time; it should show those numbers by date range in the date filter.

Example of the date filter on the agencies page:
![Screen Shot 2020-10-02 at 12 50 30 PM](https://user-images.githubusercontent.com/1767528/94948771-ddaeb600-04ad-11eb-9513-07d3a53f3180.png)

**Comment by SEGH** [comment]
I'd like to try working on this issue

**Comment by Sheeri** [comment]
Go for it, @SEGH - I've assigned it to you. Thanks for continuing to work on O-FISH - it's awesome to have you contributing so much!

**Comment by SEGH** [comment]
@Sheeri I was able to get this working, but only by also modifying the getAgencies function in Realm. That function currently only returns the total number of boardings and violations, so I added date to the $match in that function. Should I go ahead and make my pull request for the changes to the web repository even though the page doesn't work without the new function?

**Comment by Sheeri** [comment]
Hi @SEGH yes, go ahead and add that PR in - you can also add a PR to the o-fish-realm code - the file should be https://github.com/WildAid/o-fish-realm/blob/main/WildAidDemo/functions/getAgencies/source.js

(or, if you clone the o-fish-realm repository, it will be in:
WildAidDemo/functions/getAgencies/source.js)

We can change Realm first, then merge in the web code.
