### ISSUE TITLE
Take Boarding Information filters out on maps of boardings

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#234]
On the Boardings page - /#/boardings - the +Filter button (next to the Map checkbox) has a section of Boarding Information including: Date; Date from; Date to; Time; Location. 

Take all those checkboxes and the 'Boarding Information' heading out of the Filter - they are not needed.

e.g. everything in the red circle below:
![Screen Shot 2020-10-02 at 12 48 39 PM](https://user-images.githubusercontent.com/1767528/94948712-beb02400-04ad-11eb-8ada-19dfa6111438.png)

This is ONLY for the Boardings page. Other filters should remain unchanged.

**Comment by k-charette** [comment]
May I work on this issue?

**Comment by Sheeri** [comment]
Since you've finished work on the other PR, I've assigned this to you! Please submit your PR whenever it's ready.
