### ISSUE TITLE
Crew member page should show unique vessel names only

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#237]
On the crew page /#/crew - the vessel field is a comma-separatred list of vessels from all the boardings. Each vessel name should only show up once even if it is in multiple boardings. Also, empty strings should not show up:

In this example:
- the first vessel, ', , ,' is several boardings with an empty string in the vessel name. This should just be the empty string, and show up blank, like the license number.
- The last entry for Abramo Dawson shows the Lucia Lucifer twice in the vessels list, it should only show up once.
![Screen Shot 2020-10-02 at 12 26 33 PM](https://user-images.githubusercontent.com/1767528/94946691-83602600-04aa-11eb-8b1a-38601ff3cdb7.png)

**Comment by mdegis** [comment]
I would like to take a shot on this one too 🕺

**Comment by Sheeri** [comment]
Thanks for offering! Glad you're back for more :D I've assigned this to you.
