### ISSUE TITLE
Vessel page should show unique home port names only

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#238]
On the vessels page /#/vessels - the home port field is a comma-separatred list of home ports from all the boardings. Each home port name should only show up once even if it is in multiple boardings.

For example, we see "Alaska" here. Also, the empty string should not be displayed (we see ",Alaska,Alaska,Alaska" because there is an empty string for home port in a boarding):
![Screen Shot 2020-10-02 at 12 24 38 PM](https://user-images.githubusercontent.com/1767528/94946504-4005b780-04aa-11eb-8636-d66ae09c9a24.png)

**Comment by antwonthegreat** [comment]
I'd like to work on this one. Is there a simple way to have a vessel record show on my sandbox agency?

**Comment by Sheeri** [comment]
Hi @antwonthegreat - I have added 2 records to the database under your agency. Can you let me know if that works for you?

**Comment by antwonthegreat** [comment]
Looks good. Thanks!
