### ISSUE TITLE
Violations on View Boarding page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#239]
Right now violations don't show up on the View Boarding page - /#/boardings/view - they should appear as per https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/420742269_Boarding_Record

**Comment by mcastre** [comment]
@o-fish-wildaid @Sheeri I would like to try this issue.

**Comment by Sheeri** [comment]
Hi @mcastre - as per our Contribution Guidelines - https://wildaid.github.io/contribute/index.html - we prefer to assign issues to folks to work serially - that is, only one issue per person at a time. You're already assigned issue #240. We do this is in order to be fair to everyone participating, in case this is an issue someone else really wants and can work on it before you can.

If you'd like, we can unassign #240 and assign this one to you, or you can work on #240 and let us know when you submit the PR, and we can assign this one to you if nobody else has asked first.

Thanks so much for being so eager to help the project!

**Comment by mcastre** [comment]
@Sheeri ah ok its no problem! ill just work on #240

**Comment by pattimcletchie** [comment]
@Sheeri I'd like to give this a try -- I may need some help but I am in the digital ocean hacktoberfest zoom with you now.

**Comment by Sheeri** [comment]
Hello @pattimcletchie, thanks for offering to work on this! I have assigned it to you.

**Comment by pattimcletchie** [comment]
@o-fish-wildaid @am-MongoDB @Sheeri I am having an issue getting the map to work on ` <ViolationsSection>` on the boarding-view.component.js -- `Cannot read property 'map' of undefined` I feel like if I knew the codebase better I'd be able to track down this bug. Any thoughts?

**Comment by Sheeri** [comment]
Which page does this correspond to?  is it /#/boardings/null or /#/boardings/view/RECORD_ID or something else?

**Comment by pattimcletchie** [comment]
Hi @Sheeri, sorry for the delay (work got in my way). The page in question is `/#/boardings/view/RECORD_ID`. Here is a screenshot for reference just in case that is helpful.

<img width="1314" alt="Screen Shot 2020-10-22 at 8 04 27 PM" src="https://user-images.githubusercontent.com/12242330/96944919-d7ef3380-14a1-11eb-9543-9718f8b2b8a8.png">

**Comment by Sheeri** [comment]
Hi @pattimcletchie - ugh, that's a frustrating issue. I hunted it down on the sandbox server, it had to do with other code not being up to date, which I've fixed on the sandbox server. Can you try now?

**Comment by Sheeri** [comment]
Hi @pattimcletchie - are you still planning on working on this for hacktoberfest?

**Comment by pattimcletchie** [comment]
@Sheeri yes, sorry! Work has been insane. I will work on this tonight.

**Comment by pattimcletchie** [comment]
@Sheeri I am getting the exact same error and I pulled down the latest. Not sure what is going on.

**Comment by Sheeri** [comment]
Hrm.... maybe try making a new sandbox user and agency?  I wonder if there's some data weirdness going on. The view boarding page works for me :(

**Comment by Sheeri** [comment]
Some things to check:

in boarding-view.component.js at the top, is this line uncommented?
```import ViolationsSection from './violations/violations.section'; ```

If you're still getting that, then this file needs debugging: - src/components/boardings/boarding-view/violations/violations.section.js

I can see right away that the violations section is weird looking, it looks like that's more of an editing page than a view page. Check out  src/components/boardings/boarding-view/crew/crew.section.js as more of a template. 

As for the actual error - when something is undefined, look to where it's assigned. In this case it looks like 'values' is the undefined thing that 'map' can't use. 

'values' is defined at the beginning of the 'render()' portion as:
```const values = this.state.data;```

and this.state.data is defined at the top as:
```data: props.dataObject.violations```

You're passing ```<ViolationsSection dataObject={boarding} /> ```, so what I'd do is at the beginning of the render section, do something like:
```console.log(this.state);```
and see what you get (you may need to comment out the map part of the page so the errors don't interfere with loading the page).

My bet is that 'violations' isn't an object in the boarding object. (and from my own knowledge of the schema, it's more likely to be something like inspection.summary.violations or something)

Hope that helps!

**Comment by Sheeri** [comment]
This has been fixed.
