### ISSUE TITLE
Map on View Boarding page

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#240]
A map should appear with the location on the View Boarding page - /#/boardings/view - as per the design at https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/420742269_Boarding_Record

**Comment by mcastre** [comment]
@o-fish-wildaid @Sheeri Hi! id like to work on this issue. Do you have a preference of which map service you would like to use? Google Maps, MapBox, etc.

**Comment by Sheeri** [comment]
Hi @mcastre - we do not have a particular preference; however, we do have some requirements:

- Our software is licensed under the Apache 2.0 license, so anything we add to our code should be either Apache 2.0 license or the more permissive MIT license.

- Show location on the map when given latitude and longitude

- Be able to get latitude and longitude from user manipulation (e.g. mouse click on the map)

- A future requirement is to show an area defined by a polygon of lat/lon coordinates, in addition to the map point. The polygon would be retrieved from the database. A sample polygon is:
[ -89.92721557617188, -0.6522991408974571],
[ -91.47079467773438, -1.1493674854885385],
[ -91.80313110351562, 0.037078854833771706],
[ -91.07528686523438, 0.2705373247971191],
[ -89.92721557617188, -0.6522991408974571]

That's how it would be retrieved from our database, and the format is [longitude, latitude]

**Comment by mcastre** [comment]
@Sheeri ok ill give it a go!

**Comment by mcastre** [comment]
@Sheeri is there a Slack channel or something to report an issue with building the o-fish app? im having trouble importing the sample data from o-fish-realm using the steps outlined at [here](https://wildaid.github.io/foundation/2020/06/09/Data-Import.html).

when i run this command my terminal hangs after i enter my password.

` mongorestore --drop --uri "mongodb+srv://mcastre@ofish.cgr73.mongodb.net/wildaid" /Users/martincastre/Desktop/martin-env/o-fish-realm/WildAidSampleBackup`

**Comment by Sheeri** [comment]
Hi! At the bottom of every build page is a link to the troubleshooting page at https://wildaid.github.io/problems/, which points to the community forums for that type of help: https://developer.mongodb.com/community/forums/tag/o-fish/

It looks like you put the username in the URI but not your password - the uri should be:

"mongodb+srv://mcastre:PASSWORD@ofish.cgr73.mongodb.net/wildaid"

if that doesn't clear things up,  defibrillator ask on the forum (but please don't post your password....)

**Comment by Sheeri** [comment]
@mcastre were you able to import the realm app? We do have [office hours tomorrow](https://live.mongodb.com/events/details/mongodb-hacktoberfest-presents-o-fish-office-hours-hacktoberfest-5/) if you want synchronous help - I'll be there!

**Comment by Sheeri** [comment]
Closing; this works and was an issue with permissions. https://github.com/WildAid/o-fish-web/blob/main/src/components/boardings/boarding-view/basic-info/basic-info.section.js
