### ISSUE TITLE
Web: Use the bucket pattern rather than skipping - web

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#25]
When iterating using `skip` to page through a collection it works but it inefficient when working through many pages. A better pattern is the bucket pattern: [https://www.mongodb.com/blog/post/paging-with-the-bucket-pattern--part-1]

**Comment by Sheeri** [comment]
The pattern is a schema design pattern, and I don't see us changing the schema design to bucket for pagination of boarding records....
