### ISSUE TITLE
Internationalize fields on vessel view page

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#262]
The Vessel View page has some fields that are not internationalized.

**To Reproduce**
Set browser language to Spanish (ecuadorian/latin american)
Log in
Go to a vessel view page

<img width="1148" alt="Screen Shot 2020-10-04 at 10 04 19 AM" src="https://user-images.githubusercontent.com/1767528/95017714-fabbc400-0628-11eb-8259-1c0727e20656.png">

Please add in the translations into src/components/vessels/vessel-view/vessel-view.component.js, as part of the TABLE group (just like TABLE.DATE, TABLE.CAPTAIN, etc), for:
PERMIT_NUMBERS
FLAG_STATES
HOME_PORTS
CAPTAINS

**Desktop (please complete the following information):**
 - Mac OS X
 - Firefox
 - 80.0.1

**Comment by Sheeri** [comment]
found while checking #11 #261

**Comment by mdegis** [comment]
I think I can help you with this 👷

**Comment by Sheeri** [comment]
Awesome! We'd love your help. I've assigned this to you.
