### ISSUE TITLE
Ensure that no deployment-specific values hit GitHub

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-web#267]
**Describe the bug**
Ensure that no deployment-specific values (e.g. the Realm app-id can accidentally be pushed to GitHub

**Comment by o-fish-wildaid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [o-fish-web really .gitignore the config file](https://trello.com/c/thUX8z8v/390-o-fish-web-really-gitignore-the-config-file)
