### ISSUE TITLE
Web: Search results should show results in order of relevance not grouped by vessel/crew/boardings

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#27]
Search results should show results in order of relevance not grouped by vessel/crew/boardings. See: [https://mongodb.invisionapp.com/share/KMX7FJCS3VY#/screens/416880779_Field_Officer-Home] This is about the search results page which can be seen [https://mongodb.invisionapp.com/share/KMX7FJCS3VY#/screens/416880781]

**Comment by Sheeri** [comment]
duplicate
