### ISSUE TITLE
Localization/CSS changes to Agencies Dashboard

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#274]
In PR #271 breadcrumbs for agencies dashboard were added. The text "Dashboard/agencies" is hard-coded instead of using a translation, and it uses inline CSS. Please internationalize the text and use the same styling as the existing links on the page use (e.g. "View Boardings").

**Comment by Sheeri** [comment]
cc @SEGH

**Comment by SEGH** [comment]
Thanks, @Sheeri! I'd like to work on this

**Comment by Sheeri** [comment]
Thanks, @SEGH, I've assigned this to you.
