### ISSUE TITLE
useEffect React hook needs a list of dependencies

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#278]
Describe the bug
When I build the app locally with 'npm start', I get a warning.

To Reproduce

1. check out code
2. copy src/config.js.tmpl to src/config.js
3. set realm-app-id in src/config.js to: wildaidsandbox-mxgfy (no other changes needed)
4. npm install && npm start
5. See warning:
**./src/components/charts/chart-box.component.js
  Line 37:3:  React Hook useEffect contains a call to 'setFilter'. Without a list of dependencies, this can lead to an infinite chain of updates. To fix this, pass [filter, options, boxId] as a second argument to the useEffect Hook  react-hooks/exhaustive-deps**

**Expected behavior**
The warning should not appear

**Comment by fandok** [comment]
can i take a look on this?

**Comment by Sheeri** [comment]
Hello @fandok, thanks for offering to work on this! I have assigned it to you.

**Comment by fandok** [comment]
thanksss, on it
