### ISSUE TITLE
New user validation bug

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#280]
**Describe the bug**
New user validation bug

**To Reproduce**
1. Go to Create User page as either global admin or agency admin role
2. Select a role before focusing on any other fields
3. Create User button never becomes enabled, even if the rest of the form is then filled out.

**Expected behavior**
Create User button should be enabled when Email and Role are filled out, and only disabled when both do not have values.

Found when testing #272

**Comment by crowtech7** [comment]
Was this resolved?

**Comment by Sheeri** [comment]
It was not resolved. Would you like to work on it?

**Comment by crowtech7** [comment]
Yes, I would like to try!

**Comment by Sheeri** [comment]
OK, @crowtech7 - I've assigned this to you. (you've got this - literally!)

**Comment by Sheeri** [comment]
@crowtech7 are you still planning to work on this?

**Comment by crowtech7** [comment]
@Sheeri yes I am. This one is stretching me and my day job has been ramping up. I'll continue to work on it but I am totally fine if someone else can get it done sooner. Feel free so assign someone else if needed!

**Comment by Sheeri** [comment]
Nah, you're good! We do have office hours tomorrow if you want some help walking through what's stretching you! https://live.mongodb.com/events/details/mongodb-hacktoberfest-presents-o-fish-office-hours-hacktoberfest-5/#/

**Comment by crowtech7** [comment]
Hey @Sheeri sadly I need to be unassigned from this task. I'll continue to contribute when I have some more time. Thank you for all your help!

**Comment by Sheeri** [comment]
Unassigning. It was a pleasure to work with you and when you have more time we'll welcome you back!
