### ISSUE TITLE
Add restore password page

### ISSUE THREAD

**Issue by ayushjainrksh** [WildAid/o-fish-web#315]
**Is your feature request related to a problem? Please describe.**
When a user tries to reset the password, they are redirected to a blank page that says `Restore password page (no designs yet)`.

**Describe the solution you'd like**
I'd like to work on adding a password reset page that sends a `reset password` link to user's email which they can use to reset their password.

**Comment by Sheeri** [comment]
This is a great issue to work on! Do you have a design in mind? Does it add any database fields? Is there a similar project whose code you can point us to?

I have assigned this to you.

**Comment by ayushjainrksh** [comment]
@Sheeri I'd consider the same design as the login page (to keep it consistent). Let me know if that works or we can try a different design. My initial thoughts are to send an email with the password reset link that utilizes already existing user service in MongoDB stitch. I don't think there would be a need to add any database field but I'll try it out and let you know.

https://github.com/WildAid/o-fish-web/blob/14fbb743b9061e79ac4a48c8b9eb63a9194f66c6/src/services/user.service.js#L61-L71

**Comment by ayushjainrksh** [comment]
### Proposed password reset screen

![Screenshot from 2020-10-17 00-50-37](https://user-images.githubusercontent.com/33171576/96300240-d7bee600-1012-11eb-8915-6fca6a66fa9b.png)

**Comment by Sheeri** [comment]
Hi @ayushjainrksh - I like this idea! Please go ahead and implement it.

**Comment by ayushjainrksh** [comment]
@Sheeri I've added an initial PR with the implementation of the discussed feature.
