### ISSUE TITLE
Fix logo and text input labels on login page

### ISSUE THREAD

**Issue by CR96** [WildAid/o-fish-web#344]
**Is your feature request related to a problem? Please describe.**
Labels for the application logo and text input fields on the login page are not properly read when using a screen reader.

**Describe the solution you'd like**
Correctly associate labels with their respective elements.

**Comment by Sheeri** [comment]
@CR96 accepted as an issue, this is ready to work on. Would you like it to be assigned to you?

**Comment by CR96** [comment]
@Sheeri Yes, please!

**Comment by Sheeri** [comment]
@CR96 the issue is yours!
