### ISSUE TITLE
Search results for a vessel should go directly to that vessel

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#353]
**Describe the bug**
Search results for a vessel currently get redirected to the "Vessels" page for the search item, not the actual record clicked.

**To Reproduce**
1. Log in
2. Make sure "All" is set in the search bar:
![Screen Shot 2020-10-28 at 4 10 55 PM](https://user-images.githubusercontent.com/1767528/97491169-2be19880-1938-11eb-83d2-fcd3244716d7.png)

3. Put in a search term that will match at least one vessel
4. Click on the vessel that shows up in the results, e.g. here I searched for "boat" and will click on "My Boat":
![Screen Shot 2020-10-28 at 4 12 01 PM](https://user-images.githubusercontent.com/1767528/97491300-52073880-1938-11eb-99b9-356d0aa04ef6.png)

5. The page that shows up is the vessel search page, not the individual boarding record. e.g. this is the page that shows up (it has a url of /#/vessels/null):
![Screen Shot 2020-10-28 at 4 12 29 PM](https://user-images.githubusercontent.com/1767528/97491336-63504500-1938-11eb-8ead-6907e739ece2.png)

When it should be this (with a URL of https://wildaidsandbox-mxgfy.mongodbstitch.com/#/vessels/view/{"vessel.permitNumber":"12345","vessel.name":"My Boat"}):

![Screen Shot 2020-10-28 at 4 13 30 PM](https://user-images.githubusercontent.com/1767528/97491427-87138b00-1938-11eb-8650-dad49abfd7fd.png)

**Expected behavior**
Instead of redirecting to the **vessels** page, the search should redirect to the appropriate **vessels/view** page.

**Comment by lenmorld** [comment]
Hi @Sheeri 
can I take this one?
I was looking at https://github.com/WildAid/o-fish-web/issues/63
so I've been familiar around these parts anyways

but since it's a good first issue, maybe it's better to leave it open for others who are new to the repo
I'll let you decide :)

**Comment by Sheeri** [comment]
Hi @lenmorld - I'm SO GLAD you are still working on O-FISH! Now that hacktoberfest is over, I don't foresee a ton of new people randomly finding us :D I've assigned it to you
