### ISSUE TITLE
Search menu default should be "All" on home page

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#366]
**Describe the bug**
On the home page, the search menu defaults to "Agency" for an Agency administrator and "Global" for a global administrator. It correctly shows "All" for a field officer, and should show "All" for the other roles as well.

**Screenshots**
![Screen Shot 2020-11-09 at 3 18 19 PM](https://user-images.githubusercontent.com/1767528/98591825-cded7300-229e-11eb-94b6-03d210bf0eda.png)

![Screen Shot 2020-11-09 at 3 18 31 PM](https://user-images.githubusercontent.com/1767528/98591843-d5ad1780-229e-11eb-9979-d6dd797d43d3.png)

**Comment by lenmorld** [comment]
I'd like to try this one :)

**Comment by Sheeri** [comment]
Hello, thanks for offering to work on this! I have assigned it to you, @lenmorld 

Sorry for taking so long to get back to you - I'm behind on my emails!

**Comment by Sheeri** [comment]
Oof! @lenmorld I accidentally fixed this while looking into another issue - see https://github.com/WildAid/o-fish-web/pull/375/files

**Comment by lenmorld** [comment]
Hi @Sheeri 
No worries!
Thanks for fixing it, 
I'm actually currently occupied by the Unit tests ticket
and I haven't even looked at this one, so it's all good :)
