### ISSUE TITLE
Crew Members Records Vesells list [object Object] instead of data

### ISSUE THREAD

**Issue by ljhaywar** [WildAid/o-fish-web#385]
**Describe the bug**
When viewing the Crew Members Records, the vessels listed in the table are [object Object] instead of the vessel information.

**To Reproduce**
1. Search "man" in the search bar on the home page
1. Click "see all results for 'man'"
1. In Captains & Crew, click "See all"

**Expected behavior**
Vessel information is displayed

**Screenshots**
[object Object] is displayed instead of the vessel information
![Screen Shot 2020-12-10 at 1 30 12 PM](https://user-images.githubusercontent.com/3940962/101814312-f958bd00-3aeb-11eb-93b8-6b6cddf6a16e.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Browser Version: 86.0.4240.198

**Comment by ljhaywar** [comment]
fyi @Sheeri

**Comment by Sheeri** [comment]
Cannot replicate in the current version - here's what the crew page looks like.

<img width="1440" alt="Screen Shot 2022-07-26 at 10 54 28 PM" src="https://user-images.githubusercontent.com/1767528/181150728-1f634960-abe3-4e0f-92d9-9b8bcc6d8d82.png">
