### ISSUE TITLE
Avatar is blurry and distorted for users without a profile picture

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#390]
![Screen Shot 2020-12-16 at 1 26 42 PM](https://user-images.githubusercontent.com/49571712/102390504-78de0480-3fa2-11eb-92ec-be1574fa48e9.png)

The white one on the top right of the nav should be 30px X 30px

The grey one on the dashboard should be 48px X 48px. The color should be #B9B9B9

Should also be using an SVG

![Screen Shot 2020-12-16 at 1 28 19 PM](https://user-images.githubusercontent.com/49571712/102390899-fd308780-3fa2-11eb-99cf-c7be4f66c63b.png)

[Avatar SVG](https://github.com/WildAid/o-fish-web/files/5704791/avatar.svg.zip)

**Comment by jessrichmond** [comment]
hi 👋🏼 first-time open source contributor here - is this issue up for the tackling?

**Comment by Sheeri** [comment]
Absolutely, go for it!
