### ISSUE TITLE
Navigation drop downs remain open even when the mouse leaves the dropdown area. They should close.

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#399]
Once the mouse leaves the dropdown menu from the nav, it should close.

https://user-images.githubusercontent.com/49571712/110979266-615cb080-8332-11eb-8ae6-f0e81b5bf8ef.mp4

**Comment by jflip** [comment]
Mind if I pick this one up?

**Comment by jflip** [comment]
No worries! Thanks 👍
