### ISSUE TITLE
When editing your own account, clicking "Cancel" on the bottom doesn't do anything

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#419]
https://user-images.githubusercontent.com/49571712/111006755-5ec28100-835b-11eb-8b3b-d67958e8bba2.mp4

This should take the user back to the screen they were on.

**Comment by lenmorld** [comment]
@Sheeri Can I work on this?
Also, where should it go after clicking Cancel?
Maybe home page, or previous page (we might have this info in react router route objects) ?

**Comment by Sheeri** [comment]
Absolutely, please do! It should go back to the screen they were on - previous page.
