### ISSUE TITLE
As a field officer in a newly created agency, I can see boardings from other agencies in the boardings table on boardings page 

### ISSUE THREAD

**Issue by MikeyDubs** [WildAid/o-fish-web#421]
Field officers should only be able to see boardings from their own agency, unless other agency data has been shared with them. As a field officer in an agency with no boardings, I can still see boardings from other agencies in my agency. Clicking on one of those boardings doesn't work though.

**Comment by Sheeri** [comment]
This was fixed Dec. 5th, internally in the Realm functions - they needed to be set to "Application User Authentication" or similar - not System Authentication.
