### ISSUE TITLE
Default to boarding records list should be descending by date

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#443]
Default to boarding records list should be descending by date - on Boarding records -> Boardings

**Comment by mmhuseynov** [comment]
I fixed this issue on the MongoDB Realm. @Sheeri please check that.

**Comment by Sheeri** [comment]
Confirmed! The code itself is stored in the repo at https://github.com/WildAid/o-fish-realm; I will update the change to searchFacetByBoardings there.

**Comment by Sheeri** [comment]
Oh, one thing - why isn't sortingTerms added to line 48? https://realm.mongodb.com/groups/5ef9c84380490a4859613112/apps/5f227996113931f95d7aea5e/functions/60a40bdb90394cecd1825ca6

**Comment by Sheeri** [comment]
Oh, I figured it out, because it's the amount, total count, and doesn't need to be sorted.....
