### ISSUE TITLE
User.createdOn needs to be a date rather than a string

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-web#46]
This is needed so that it can be parsed as a date by the Realm schema checks. At the same time, need to change `createdOn` in the [realm schema](https://github.com/WildAid/o-fish-realm/blob/main/WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json) back to type `date`.

The [associated realm issue](https://github.com/WildAid/o-fish-realm/issues/55) should be fixed at the same time

**Comment by Sheeri** [comment]
@am-MongoDB has this been fixed? I see a change merged. Let's close if it's fixed.
