### ISSUE TITLE
User creation page design

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#49]
The user creation page is great! However, there are a few design changes. See https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/422349126

First Name and Last Name are on the same line, everything else has its own line.
The role should be a drop down with at most 4 items as per https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/422349130_Global_Admin-Users-Create_New-Role-
Global Admin
Agency Admin
Group Admin
Field Officer

Only a Global Admin can make another Global Admin, so only a global admin sees all 4 choices.
An Agency Admin should see the 3 choices under Global Admin but not see Global Admin.

A group admin and a field officer cannot create users and should never see this page.

**Comment by am-MongoDB** [comment]
I'll update the `User` schema - so this issue should be coordinated with https://github.com/WildAid/o-fish-realm/issues/70
