### ISSUE TITLE
404 Error when reloading page

### ISSUE THREAD

**Issue by am-MongoDB** [WildAid/o-fish-web#5]
A 404 error message is displayed when you reload the browser page - it should refresh the page properly instead

**Comment by Azzoo** [comment]
I think this is something related to production server. When i use react dev server locally -- no issues with refresh.

**Comment by am-MongoDB** [comment]
We've been testing with MongoDB Realm hosting, but I've also just uploaded the build to a regular web server and am still getting errors on reload (try http://portal.clusterdb.com/ and then reload)
