### ISSUE TITLE
Search Results clickable

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#55]
When you first search on the home page and get autocomplete results - the only thing you can click is 'See all results for 'search term''. A user should be able to click on the vessel or crew or boarding result if that's exactly the one they want; so they do not have to click on 'See all results for 'search term'' and then click 'See all' on the next page and THEN click on the same record they saw in the autocomplete.

**Comment by Sheeri** [comment]
Blocked waiting design.

**Comment by Sheeri** [comment]
Design is at https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/422125610
With InVision, you can click on areas and see functionality.

Clicking on the search bar shows an autocomplete search for 'Predtr bluefin' - the screen at https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/420742264. From this screen, you can click on:

1) The vessel Predator, which brings you to the vessel record for predator (you end up at https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/427645087)

2) The crew member Nemo Marlin, which brings you to the crew record for Nemo Marlin (this page - https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/427643118)

3) The Boarding record for March 16, 2020, which brings you to that boarding record (this page - https://mongodb.invisionapp.com/share/VJXLVXNPGW4#/screens/420742269)

- See all results for "Predtr bluefin" - this functionality was implemented.

The scope of this ticket is to implement the functionality described in 1,2 and 3, specifically:
 
1) Link each vessel search result: Use the vessel name and permit number to link to  #/vessels/view/{%22vessel.permitNumber%22:%22PERMIT_NUMBER%22,%22vessel.name%22:%22VESSEL_NAME%22} - you will need to replace PERMIT_NUMBER and VESSEL_NAME in the URL 

2) Link each crew search result: Use the crew name and license number to link to #/crew/view/{%22crew.license%22:%LICENSE_NUMBER%22,%22crew.name%22:%22CREW_NAME%22} - you will need to replace LICENSE_NUMBER and CREW_NAME in the URL

3) Link each boarding search result to #/boardings/view/BOARDING_RECORD_ID - you will need to replace BOARDING_RECORD_ID in the URL
