### ISSUE TITLE
Search Results page clickable fields

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#56]
On the search_results page after clicking 'See all results for 'search term' a user can only click on 'See all' for Records of Vessels or Captains & Crew or Boardings. Users should also be able to click on the vessel or person or boarding record shown on the page and go directly to that record - as if they had clicked through to the 'See all' page and then clicked that record. It will save 2 clicks and is what the users expect.

**Comment by Sheeri** [comment]
Blocked waiting design.
