### ISSUE TITLE
Results in search autocomplete should go to the appropriate page

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#62]
If you type in the search box, you get autocomplete. A user should be able to click on any of the listings there to go to the vessel, crew or boarding page for that record. This saves at least one click, and usually saves 2 clicks, from the user.

**Comment by Sheeri** [comment]
Blocked waiting design.

**Comment by Sheeri** [comment]
Those should be clickable in the list item, to go straight to the "#/boardings/view/" page for boardings, "#/vessels/view/" page for vessels and "#/crew/view/" for crew members.

**Comment by sourabhbagrecha** [comment]
Interesting, can I take this up? @Sheeri

**Comment by Sheeri** [comment]
Hello @sourabhbagrecha, thanks for offering to work on this! I have assigned it to you.
