### ISSUE TITLE
Search results page should redirect to vessel and crew for those listings

### ISSUE THREAD

**Issue by Sheeri** [WildAid/o-fish-web#63]
Like issue #28, on the search results page, vessel and crew listings should be clickable and redirect to those pages.

**Comment by lenmorld** [comment]
Hi I'd like to try this one

**Comment by Sheeri** [comment]
Hello @lenmorld, thanks for offering to work on this! I have assigned it to you.

**Comment by Sheeri** [comment]
@lenmorld do you still want to work on this one? To replicate:
- Login
- Use the search bar at the top to search for something
- On the results part that pops up, click the bottom link that says "See all results for SEARCH_STRING"
- From there, clicking on the boarding, vessel, or crew that shows up should go to the boarding or vessel or crew page.

Currently it looks like the boarding link is clickable but doesn't actually bring up a record, and nothing happens if you click on vessel or crew.

I'm sure it will be very similar to the work in https://github.com/WildAid/o-fish-web/pull/327 so it shouldn't be too hard...

**Comment by lenmorld** [comment]
Hi @Sheeri 
Yes, i did a hard reset on my branch, that's why it got closed.
I'm currently looking at it, but also blocked by the data not loading
https://developer.mongodb.com/community/forums/t/typeerror-agency-inboundpartneragencies-is-undefined/10822
