### ISSUE TITLE
Change password on first login

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#76]
On first login - change password. Sheeri has a plan for this.

**Comment by Azzoo** [comment]
Does it means for the first login user shoul see only MyAccound page ?

**Comment by Sheeri** [comment]
For the first login, they should be taken directly to the ["Change Password" screen](https://mongodb.invisionapp.com/share/MYXRXC2T2H3#/screens/422362396)

As a reminder, here is the [design document link for change password functionality](https://docs.google.com/document/d/1rDXmdlB3lfqAb7uAhR1u96LbyNaUyl3_2t2O_C0kI_E/edit?pli=1#bookmark=id.6w11bfnm0r4g)

**Comment by Sheeri** [comment]
This is no longer needed, as custom first passwords are allowed to be defined.
