### ISSUE TITLE
Create User Requires email

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-web#77]
On the Create User screen - email needs to be a required field.

**Comment by antwonthegreat** [comment]
Can I work on this one?

**Comment by Sheeri** [comment]
Hi @antwonthegreat - according to our contribution guidelines at https://wildaid.github.io/contribute/index.html - we will only assign one issue per person at at time. When you have submitted a PR on your previous issue, you can make a comment here and if nobody else has taken up the issue, we will assign it to you.

**Comment by antwonthegreat** [comment]
I finished up that previous issue. Can I take this one?

**Comment by Sheeri** [comment]
Absolutely! It's assigned to you now.
